name: Trigger build

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "new version published"

      - name: Trigger build for library-consumer (to check the new version)
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/tonisanta/library-consumer/actions/workflows/go-build.yml/dispatches \
          -d '{"ref":"main"}'
